#!/bin/bash

usersfile=/mnt/sambashare/users.txt

if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root"
    exit 1
fi

while read user; do
     getent passwd ${user//[$'\t\r\n']} > /dev/null

    if [ ! $? -eq 0 ]; then
        useradd -G root -s /bin/bash -m ${user//[$'\t\r\n']} > /dev/null
        passwd -d ${user//[$'\t\r\n']} > /dev/null
    fi

done <$usersfile
